### ISSUE TITLE
Add Material-UI to the client directory

### ISSUE THREAD

**Issue by Rmckays** [Software-Development-Mastermind/sdmm-flashcards#5]
Add the npm package for material-ui to the client project.

**Comment by chrisdetmering** [comment]
Are we okay with using Roboto font? That is what material UI is designed in mind to use, at least according to the docs.

**Comment by chrisdetmering** [comment]
@Rmckays I did this. Can this issue be closed?

**Comment by chrisdetmering** [comment]
I added material UI to the client project
