### ISSUE TITLE
Create Theme for UI using Material-UI and Theme Provider

### ISSUE THREAD

**Issue by Rmckays** [Software-Development-Mastermind/sdmm-flashcards#6]
Create the overall theme for the front-end using a ThemeProvider in material-ui. Wrap the client element with the Theme provider and configure.

**Comment by chrisdetmering** [comment]
@Rmckays I have the colors below as the colors that I grabbed from the Software Development Mastermind jpg image that Andy shared. 

Blue: #054771
Gray: #6d6e72

Are there going to be other gradients of these colors that we are going to use?

**Comment by andysterks** [comment]
I am thinking white can be the other color that we can use. @Rmcakys feel free
to add in anything here as well.  





On Fri, Mar 19, 2021 7:18 PM, Chris Detmering ***@***.***  wrote:


@Rmckays  I have the colors below as the colors that I grabbed from the Software
Development Mastermind jpg image that Andy shared.

Blue: #54771
Gray: #6d6e72

Are there going to be other gradients of these colors that we are going to use?

**Comment by chrisdetmering** [comment]
I created the theme for UI and added the Theme Provider 

see Cd theme provider #13
